name: ChunkTP
version: '${pluginVersion}'
main: world.thearchive.chunktp.ChunkTP
description: Minecraft Paper server plugin that allows players to teleport to specific chunk coordinates
author: thearchive.world
api-version: '${apiVersion}'
folia-supported: false

# Paper plugin features
permissions:
  chunktp.use:
    description: Allow teleporting to chunk coordinates
    default: true
